<?php
$page = "home";
$title = "Welcome to BSA Troop 39 | Matthews, NC";
include ("header.php");
?>
<style type="text/css">
a.trainingLink {
	-moz-box-shadow:inset 0px 1px 0px 0px #f29c93;
	-webkit-box-shadow:inset 0px 1px 0px 0px #f29c93;
	box-shadow:inset 0px 1px 0px 0px #f29c93;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #fe1a00), color-stop(1, #ce0100) );
	background:-moz-linear-gradient( center top, #fe1a00 5%, #ce0100 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fe1a00', endColorstr='#ce0100');
	background-color:#fe1a00;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #d83526;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #b23e35;
}a.trainingLink:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ce0100), color-stop(1, #fe1a00) );
	background:-moz-linear-gradient( center top, #ce0100 5%, #fe1a00 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ce0100', endColorstr='#fe1a00');
	background-color:#ce0100;
		text-decoration:none;

}a.trainingLink:active {
	position:relative;
	top:1px;
}

.trainingLink2 {
	-moz-box-shadow:inset 0px 1px 0px 0px #a4e271;
	-webkit-box-shadow:inset 0px 1px 0px 0px #a4e271;
	box-shadow:inset 0px 1px 0px 0px #a4e271;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #89c403), color-stop(1, #77a809) );
	background:-moz-linear-gradient( center top, #89c403 5%, #77a809 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#89c403', endColorstr='#77a809');
	background-color:#89c403;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #74b807;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #528009;
}.trainingLink2:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #77a809), color-stop(1, #89c403) );
	background:-moz-linear-gradient( center top, #77a809 5%, #89c403 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#77a809', endColorstr='#89c403');
	background-color:#77a809;
		text-decoration:none;

}.trainingLink2:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>

<table border="0" cellspacing="3" width="802" id="AutoNumber2" cellpadding="5" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="213" bgcolor="#C6BA9B" bordercolorlight="#415223" bordercolordark="#415223" valign="top" rowspan="2">
            
            <p style="line-height: 150%; margin-top: 0; margin-bottom: 0" align="center">
            <b><font face="Arial" style="font-size:18px" color="#900">Outing Info &amp; Sign Up</font></b></p>
             <hr color="#415223">



<h4 style="font:bold 12px Verdana, Arial, sans-serif; color:#900;margin-bottom:0;">Rafting Trip: August 15<BR><span style="color:#FFF; text-shadow:1px 1px 1px #333;">(Deadline: 8/4)</span></h4>
<p style="margin:0 8px 8px 8px;  font:11px Verdana, arial, sans-serif; color:#003300;" align="left">Hot Springs Resort & Spa Family Camp Grounds and camp in the primitive
camping area. We will be on the River by 9:00 am on Saturday for a 9-mile rafting trip with a
cook-out lunch along the way. Back to the camp afterwards for some chill time, dinner and a
campfire program. Breakfast and devotional on Sunday morning before we head back to Matthews.
<br>
			<a href="docs/permission/T39 14-08 Rafting-Info.pdf" target="_blank">Information Sheet >></a>
			<br><a href="docs/permission/T39 14-08 Rafting-Permission.pdf" target="_blank"><strong>PERMISSION >></strong></a>
			</p> 

			
<h4 style="font:bold 12px Verdana, Arial, sans-serif; color:#900;margin-bottom:0;">Fishing Trip: Sept. 12<br><span style="color:#FFF; text-shadow:1px 1px 1px #333;">(Deadline: 8/25)</span></h4>
<p style="margin:0 8px 8px 8px;  font:11px Verdana, arial, sans-serif; color:#003300;" align="left">We will be camping in Murrell's Inlet, SC on the grounds of the Belin United Methodist Church on
Friday and Saturday nights - chartered organization for BSA Troop 396. The campsite has bathrooms
and running water and is within walking distance of the Crazy Sister's Marina - where we have
chartered an early Saturday A.M. departure.
<br>
			<a href="docs/permission/T39 14-09 Ocean Fishing-Info.pdf" target="_blank">Information Sheet >></a>
			<br><a href="docs/permission/T39 14-09 Ocean Fishing-Permission.pdf" target="_blank"><strong>PERMISSION >></strong></a>
			</p> 

			


	 <!--	<h4 style="font:bold 12px Verdana, Arial, sans-serif; color:#900;margin-bottom:0;">MATTHEWS ALIVE!<br>Aug. 29 - Sept. 2</h4>
<p style="margin:0 8px 8px 8px;  font:11px Verdana, arial, sans-serif; color:#003300;" align="left">That's right, it's that time of year again, FESTIVAL TIME! Which means we need our entire scouting family to help out and have fun working our 2nd largest fundraiser for the troop! Click the link below to sign up for a slot (or 2 if you want)!<br><a href="http://www.signupgenius.com/go/60B0D4FAFAE2C7-matthews" target="_blank">Online Volunteer Sign Up!</a></p> 

<h4 style="font:bold 12px Verdana, Arial, sans-serif; color:#900;margin-bottom:0;">Backpacking Pisgah OR<br>Tenderfoot  Skills @ Belk<br>May 17 - 19</h4>
<p style="margin:0 8px 8px 8px;  font:11px Verdana, arial, sans-serif; color:#003300;" align="left">Pisgah Ranger District near Brevard, NC for a backpacking trip in the Pisgah National Forest. The trip consists of 4 (four) separate hikes of varying difficulty.<br><strong>Option 2</strong> for the newer scouts is a skills building weekend at Belk Scout camp to work on Tenderfoot Rank.<br>
			<a href="docs/permission/T39-13-05-PisgahBackPack.pdf" target="_blank">Pisgah Information &amp; permission</a><br>
			<a href="docs/permission/T39-13-05-Scout Skills Camping.pdf" target="_blank">Skills Information &amp; permission</a>
			</p> 	


 <!--<h4 style="font:bold 12px Verdana, Arial, sans-serif; color:#900;margin-bottom:0;">God and Church<br>Sept 12 - Nov 21</h4>
			<p style="margin:0 8px 8px 8px;  font:11px Verdana, arial, sans-serif; color:#003300;" align="left"><strong>Boys in Grades 6-8</strong> can earn the God and Church award. The God and Church program will lead
young people on a journey. It will be a faith journey with three parts: meeting Jesus, worshiping
God, and witnessing and ministering for Christ.<br><strong><em>Register by Monday August 27th!</em></strong><br>
			<a href="docs/God-and-Church-2012.pdf" target="_blank">Info &amp; Registration Form</a><br>
			Visit the Troop <a href="calendar.php">Calendar</a></p> 
			
<h4 style="font:bold 12px Verdana, Arial, sans-serif; color:#900;margin-bottom:0;">God and Life<br>Sept 12 - Dec 12</h4>
			<p style="margin:0 8px 8px 8px;  font:11px Verdana, arial, sans-serif; color:#003300;" align="left"><strong>Boys in Grades 9-12</strong> can earn the God and Life award. Program is based on the life of the Apostle Paul as recorded in Acts 9:1-31.<br><strong><em>Register by Monday August 27th!</em></strong><br>
			<a href="docs/God-and-Life-2012.pdf" target="_blank">Info &amp; Registration Form</a>
			<br>Visit the Troop <a href="calendar.php">Calendar</a></p> 
			
			
			<h4 style="font:bold 12px Verdana, Arial, sans-serif; color:#900;margin-bottom:0;">GWA Photos</h4>
			<p style="margin:0 8px 8px 8px;  font:11px Verdana, arial, sans-serif; color:#003300;" align="left">Our group is back from supertrip! Check out the Flickr Stream below to see some of our adventures!<a href="http://www.flickr.com/photos/matthewstroop39/sets/72157630497040174/">GWA Photostream</a></p>
			
            
            
            <h4 style="font:bold 12px Verdana, Arial, sans-serif; color:#900;margin-bottom:0;">*** SUPERTRIP MEETING *** <br>Monday 5/28 @ 6:30pm</h4>
			<p style="margin:0 8px 8px 8px;  font:11px Verdana, arial, sans-serif; color:#003300;" align="left"><strong>Scouts AND Parents:</strong> we are gathering together to make some of the final preperations to go out west. This is a very important meeting as we are coming up on this trip in just under 2 months and need to get everyone on the same page. This meeting should only take about 1 hr.<br><br><strong>LEADERS:</strong> We need to stay after this meeting for about an hour to discuss some of the final logistics for each leg of the trip you are resposible for. check your email for doumentation to bring to this meeting.</p>-->
            
           
			
           

<hr color="#415223">
            
			
			
            <!--webbot bot="HTMLMarkup" startspan --><script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 8,
  interval: 2000,
  width: 210,
  height: 400,
  theme: {
    shell: {
      background: '#003300',
      color: '#e8e8d0'
    },
    tweets: {
      background: '#c6ba9b',
      color: '#003300',
      links: '#b90909'
    }
  },
  features: {
    scrollbar: false,
    loop: false,
    live: true,
    hashtags: true,
    timestamp: true,
    avatars: false,
    behavior: 'all'
  }
}).render().setUser('matthewstroop39').start();
</script><!--webbot bot="HTMLMarkup" endspan --><hr color="#415223">
            <p style="margin-top: 0; margin-bottom: 0" align="center"><b>
            <font face="Verdana" size="1" color="#003300">Learn more about Troop 
            39!</font></b></p>
            <p style="margin-top: 0; margin-bottom: 0" align="center"><b>
            <font face="Verdana" size="1" color="#003300">Download the</font></b></p>
            <p style="margin-top: 0; margin-bottom: 0" align="center"><b>
            <font face="Verdana" size="1">
            <a target="_blank" href="docs/T39-Troop-Handbook.pdf">Troop 39 Handbook &amp; New Member Guide (PDF)</a></font></b></p>
           </td>
            <td width="539" align="center" valign="top" colspan="2">
			
<!--			
			<table border="0" width="95%" cellpadding="5" cellspacing="0" style="margin:15px auto;"><tr>
						<td align="center"><strong>Need BBQ or Stew?</strong> <a href="/bbq/" target="_blank" class="trainingLink2" >Order Here!</a></td>

			</table>
 ANNOUNCEMENTS
		<h3 align="center" style="color:red; margin:15px auto;">Due to weather concerns, tonight's meeting (5/6/2013) will be a normal meeting at the Eagle's Nest 7-8:30</h3>
		
TRAINING OPS LINKS
		 	<table border="0" width="95%" cellpadding="5" cellspacing="0"><tr>
			<td align="center"><strong>April 12-14<br>Wilderness First Aid</strong><br>(Older Scouts)<br><a href="/docs/Scouter Success-2013.pdf" class="trainingLink" target="_blank">Details</a></td>
			<td align="center"><strong>May 3-5<br>Leave No Trace</strong><br>(All Scouters)<br><a href="http://tinyurl.com/LNT-052013" class="trainingLink" target="_blank">Details</a></td>
			<td align="center"><strong>May 3-5<br>Wilderness First Aid</strong><br>(Adults)<br><a href="http://tinyurl.com/WFA-052013-adults" class="trainingLink" target="_blank">Details</a></td>
			</tr>
			</table>-->
			<h2 style="text-align: center; color:#B00">MANDATORY FORMS</h2>
			<a href="http://www.scouting.org/filestore/HealthSafety/pdf/680-001_ABC.pdf" target="_blank" class="trainingLink2">Annual BSA Medical Form (PDF)</a>
			<a href="http://www.scouting.org/filestore/HealthSafety/pdf/680-001_philmont.pdf" target="_blank" class="trainingLink2">PHILMONT Physical Form (PDF)</a>
            <div style="border:1px solid #003300; height:210px; padding:15px; background:url(/images/bg-eagleBannerHome.jpg) top center no-repeat #e0d9c7; margin:15px 10px 10px 10px; text-align:center;">
			<h2 style="margin-top:0;">Congratulations to our 2014<br><em>Eagle Scouts!</em></h2>
<table border="0" width="300" cellpadding="0" cellspacing="0" align="center" style="text-align:center;"><tr>
<td width="100%">
Matt Connor<br>
Will Wallace
Josiah Nelson
</td>
</tr>
<tr><td colspan="" style="padding-top:15px;"><a href="eagles.php">View All Troop 39 Eagle Scouts</a></td></tr>
</table>
			</div>
			<hr>
			<p style="margin-top: 15px; margin-bottom: 0">
            <b>
            <font size="5" face="Times New Roman" color="#003300">Welcome to Boy 
            Scout Troop 39</font></b></p>
            <p style="margin-top: 0; margin-bottom: 0"><font size="1">&nbsp;</font></p>
            <p style="margin-top: 0; margin-bottom: 0" align="left">
            <font size="1">&nbsp; </font></p>
							<div style="padding-left:15px;">
							<p align="left" style="margin-top: 0; margin-bottom: 0">
                            <font face="Verdana" color="#003300" style="font-size: 9pt">
                           It was December 11, 1941 - just four days after the Japanese bombed Pearl Harbor - that small group of boys and adults met for the first time under the leadership of Reverend Hubert Mumford of First Baptist Church of Matthews. The first meetings were held in the Matthews High School Gymnasium (where the current Matthews Elementary main Building stands) and then later in the VFW building (currently the Women’s Club). Several years later the Troop moved to the basement of the Matthews Presbyterian Church and then in the early 1980’s into the Scout Hut at the old campus of the Matthews United Methodist Church. The annual Troop Barbeque was started in 1975 and has provided funding for troop activities ever since. </font></p>
							<p align="left" style="margin-top: 0; margin-bottom: 0">
                            <font size="1">&nbsp; </font></p>
							<p align="left" style="margin-top: 0; margin-bottom: 0">
                            <font face="Verdana" color="#003300" style="font-size: 9pt">
                            Now, more than 70 years later, Troop 39 continues to 
                            provide an active program promoting outdoor skills, adventure, citizenship, leadership, and moral 
                            character-building in young men ages 11-17. Meetings are 
                            held on Monday nights from 7:00 p.m. to 8:30 p.m. in the 
                            Eagle's Nest (house next to MUMC).  </font></p>
							<p align="left" style="margin-top: 0; margin-bottom: 0">
                            <font size="1">&nbsp; </font></p>
							<p align="left" style="margin-top: 0; margin-bottom: 0">
                            <font face="Verdana" style="font-size: 9pt" color="#003300">
                            Troop 39 is led by Scoutmaster
                            <a title="Email to Frank Williams" href="mailto:scoutmastert39@gmail.com?subject=Troop 39 Information Request">Frank Williams</a>, 
                            Committee Chair
                            <a title="Email to Joe Culpepper" href="mailto:jculpepper@carolina.rr.com?subject=Troop 39 Information Request">Joe Culpepper</a> and Charter Organization Representative
                            <a title="Email to Dan Latta" href="mailto:dlatta@carolina.rr.com?subject=Troop 39 Information Request">
                            Dan Latta</a>. 
                            We are in the
                            <a title="Etowah District Homepage" href="http://mccscouting.org/Districts/Etowah.aspx">Etowah District</a> of the
                            <a title="Mecklenburg County Council Homepage" href="http://www.mccscouting.org">Mecklenburg County 
                            Council</a><font color="#003300">, and </font>Order 
                            of the Arrow
                            <a title="Order of the Arrow Catawba Lodge #459 Homepage" href="http://www.catawbalodge.org">Catawba Lodge #459</a>. 
                            Joe can also be reached by phone at 704.841.8663.</font></p></div>
            <p style="margin-top: 0; margin-bottom: 0">&nbsp;</p>
            <p style="margin-top: 0; margin-bottom: 0">
            <img border="0" src="images/scbar2.gif" width="504" height="16"></p>
			<br>
			
<!-- ######### CALL FOR VOLUNTEERS SUMMER CAMP ##########
			<div style="border:2px solid #f00; background-color:#c1ff93; font:16px Arial, helvetica, sans-serif;border-radius:8px; box-shadow:0 0 8px 2px #FFF, inset 0 0 3px #000; padding:10px; width:90%; text-align:center;">
			<h2 style="color:#F00;font:bold 23px Arial, helvetica, sans-serif;">>>>> ATTENTION! - HELP NEEDED!! <<<<</h2>
			<p>Troop, Mrs. Cole is in DIRE need of assistance this year from our adults.  Currently, she is <strong>THE ONLY ADULT</strong> at summer camp with Troop 39!  While Beth is a very capable leader...this is too big a task for even her. <br><br> We need  <strong>LEADERS AND PARENTS</strong> to consider working with her for either the whole week, part of the week, or <strong>EVEN A DAY OR TWO</strong>. This is a mission to <strong><em>SAVE SUMMER CAMP</em></strong>, contact Mrs. Cole ASAP if you can help out...</p>
			<h3>Beth Cole - 704.448.8592<br><a href="mailto:bethcole@carolina.rr.com?subject=Summer Camp Help">Send an email</a></h3>
			</div>
            <br>
######### CALL FOR VOLUNTEERS SUMMER CAMP END ##########-->
			
			<p style="margin-top: 0; margin-bottom: 0">
            <b><font face="Verdana" size="2" color="#003300">Summer Camp 
            Departure - Camp Grimes, NC - June 2013</font></b></p>
            <p>
            <img border="0" src="images/SummerCampSendoff-2013.jpg" width="525" ></p>


			<img border="0" src="images/scbar2.gif" width="504" height="16"></td>
          </tr>
          <tr>
            <td width="263" align="center" valign="top">
            <p style="margin-top: 0; margin-bottom: 0">
            <a href="http://www.mccscouting.org">
            <img border="0" src="images/council_patch.gif" width="213" height="89"></a></p>
            <p style="margin-top: 0; margin-bottom: 0"><b>
            <font face="Arial" color="#000099">Council &amp; District</font></b></p>
            <p style="margin-top: 0; margin-bottom: 0" align="left">
            <font face="Verdana" size="1">
            <img border="0" src="images/bl-bsa.gif" width="20" height="20"></font><font color="#000099" size="1" face="Verdana">&nbsp; 
            Click for the official <b> <a href="http://www.mccscouting.org">
            <font color="#000099">Mecklenburg County Council</font></a></b> and the
            <b>
            <a href="http://mccscouting.org/Districts/Etowah.aspx"><font color="#000099">Etowah 
            District</font></a></b> websites.</font></p>
            <p style="margin-top: 0; margin-bottom: 0" align="left">
            <font face="Verdana" size="1">
            <img border="0" src="images/bl-bsa.gif" width="20" height="20"></font><font color="#000099" size="1" face="Verdana">&nbsp; 
            All Council events are on the <b>
            <a href="http://www.mccscouting.org/Calendar.aspx"><font color="#000099">calendar</font></a></b>. </font></p>
            <p style="margin-top: 0; margin-bottom: 0" align="left">
            <font face="Verdana" size="1">
            <img border="0" src="images/bl-bsa.gif" width="20" height="20">&nbsp; </font>
            <font face="Verdana" size="1" color="#000099">Register for Council <b><a href="http://www.mcctraining.org"><font color="#000099">
            training</font></a></b> courses.</font></p>
           
            </td>
            <td width="276" align="center" valign="top">
            <p style="margin-top: 0; margin-bottom: 0">
            <a href="http://www.catawbalodge.org">
            <img border="0" src="images/catawba_lodge_flap.gif" width="200" height="88"></a></p>
            <p style="margin-top: 0; margin-bottom: 0"><b>
            <font face="Arial" color="#B90909">Order of the Arrow</font></b></p>
            <p style="margin-top: 0; margin-bottom: 0" align="left">
            <img border="0" src="images/bl-oa.gif" width="20" height="17"><font face="Verdana" size="1" color="#B90909">&nbsp; We are part of <b>
            <a href="http://www.catawbalodge.org">Catawba Lodge #459</a></b>.</font><p style="margin-top: 0; margin-bottom: 0" align="left">
            <img border="0" src="images/bl-oa.gif" width="20" height="17"><font face="Verdana" size="1" color="#B90909">&nbsp;
            <b><a href="http://etowah.catawba459.org/">Etowah Chapter</a></b> 
            information is here.</font><p style="margin-top: 0; margin-bottom: 0" align="left">
            <img border="0" src="images/bl-oa.gif" width="20" height="17">&nbsp;<font face="Verdana" size="1" color="#B90909">&nbsp;Find 
            all Lodge OA events in the <b><a href="http://www.catawba459.org/calendar">calendar</a></b>.</font><p style="margin-top: 0; margin-bottom: 0" align="left">
            <img border="0" src="images/bl-oa.gif" width="20" height="17">
            <font face="Verdana" size="1" color="#B90909">&nbsp;Link to </font>
            <font face="Verdana" size="1"><b><a href="http://www.oa-bsa.org">Order 
            of the Arrow National</a></b>.</font><p style="margin-top: 0; margin-bottom: 0" align="left">
            &nbsp;<p style="margin-top: 0; margin-bottom: 0" align="left">
            &nbsp;</td>
          </tr>
          </table>
		  
<?php
include ("footer.php");
?>